#!/bin/bash

function error {
	echo "OPERAZIONE NON CONSENTITA
	"	
	echo "utilizzo \"-h\" per visualizzare la lista dei comandi"
}

function help {
	echo "ADAPTUS - A simple frontend for APT
	
	"
	echo "USAGE"
	echo "	adaptus [options] [file ..]
	
	"
	echo "OPTIONS"
	echo "	-r	apt-get update
		"
	echo "	-u	apt-get update
		apt-get upgrade
		apt-get dist-upgrade
		"
	echo "	-a	apt-get update
		apt-get dist-upgrade
		"
	echo "	-i	install package[s]
		"
	echo "	-h	show this help
		"
}

function check {
	if [ $1 -gt $2 ]; then
		error
		exit 1
	fi
}

function update {
	sudo apt-get update
}

function upgrade {
	sudo apt-get upgrade
}

function dist-upgrade {
	sudo apt-get dist-upgrade
}

function install {
	shift
	sudo apt-get install $@
}

if [ $# -gt 0 ]
then
	case $1 in
		"-r") 	check $# 1
			update;;
				
		"-a") 	check $# 1
			update
			upgrade
			dist-upgrade;;

		"-d")	check $# 1
			update
			dist-upgrade;;

		"-u")   check $# 1
			update
			upgrade;;

		"-h")	help;;
	
		"-i")	install $@;;

		*)	error;;
	esac
else
	error
fi
